source 'https://rubygems.org'
gem 'rspec', '~> 3.0'
gem 'pry'

group :development, :test do
  gem 'rspec-rails', '2.14.2'
  gem "capybara-webkit"
  gem 'factory_girl_rails', '~> 4.0'
  gem 'pry-rails'
end
