source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.6'
gem 'sqlite3'
gem 'jquery-rails'
gem 'turbolinks'


group :development, :test do
  gem 'rspec-rails', '~> 3.0.0'
  gem 'jasmine'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'dotenv-rails'
end
